"""
Hand-picked evergreen NFL trivia questions.
============================================
Fun general trivia (not stat-guessing) whose answers never change over time —
no current-season stats, no "as of today" framing.

Drawn from at random by EvergreenGenerator (generators/evergreen.py).

Format: { "question": str, "choices": [4 strings], "answer": int (0-indexed) }

Add new entries anywhere in the list below.
"""

EVERGREEN_QUESTIONS = [
    {"question": "Which player invented the famous \"Lambeau Leap\"?", "choices": ["Leroy Butler", "Brett Favre", "Antonio Freeman", "Reggie White"], "answer": 0},
    {"question": "Which Hall of Famer was nicknamed \"The Minister of Defense\"?", "choices": ["Reggie White", "Michael Strahan", "Mean Joe Greene", "Lawrence Taylor"], "answer": 0},
    {"question": "Which Wide Receiver earned the nickname “Megatron”?", "choices": ["Randy Moss", "Julio Jones", "Calvin Johnson", "DK Metcalf"], "answer": 2},
    {"question": "In what year were the Lions the first winless team in NFL History, going 0-16?", "choices": ["1994", "2007", "2008", "2001"], "answer": 2},
    {"question": "What year did the Lions last win an NFL Championship before the Super Bowl era?", "choices": ["1957", "1965", "1932", "1862"], "answer": 0},
    {"question": "What iconic song did the 1985 Bears release during their Super Bowl run?", "choices": ["Packers Suck", "The Midway Monsters", "We Da Bears", "The Super Bowl Shuffle"], "answer": 3},
    {"question": "What Bears kicker became infamous for the “Double Doink” playoff miss?", "choices": ["Blair Walsh", "Cody Parkey", "Eddie Pinero", "Scott Norwood"], "answer": 1},
    {"question": "Which Vikings kicker infamously missed a potential game-winning field goal in the 1998 NFC Championship?", "choices": ["Billy Cundiff", "Scott Norwood", "Gary Anderson", "Pete Stoyanovich"], "answer": 2},
    {"question": "Which quarterback threw the famous “Minneapolis Miracle” pass?", "choices": ["Kirk Cousins", "Ryan Fitzpatrick", "Sam Bradford", "Case Keenum"], "answer": 3},
    {"question": "What Hall of Famer was known as “Prime Time”?", "choices": ["Terrell Owens", "Shannon Sharpe", "Steve Smith Sr.", "Deion Sanders"], "answer": 3},
    {"question": "Which quarterback led the Buccaneers to their first Super Bowl win in 2003?", "choices": ["Brad Johnson", "Shaun King", "Brian Griese", "Rich Gannon"], "answer": 0},
    {"question": "What was Tampa Bay’s infamous inaugural 1976 season record?", "choices": ["6-7", "2-12", "0-14", "13-1"], "answer": 2},
    {"question": "Which player ate a W?", "choices": ["Blake Bortles", "Richard Sherman", "Jameis Winston", "Jamaal Williams"], "answer": 2},
    {"question": "Which player was famous for the quote, “Ice up, son”?", "choices": ["Brandon Marshall", "Jalen Ramsey", "Steve Smith Sr.", "Chad “Ochocinco” Johnson"], "answer": 2},
    {"question": "Which player became the first in Panthers history to record 1,000 rushing and 1,000 receiving yards in the same season?", "choices": ["Stephen Davis", "Christian McCaffrey", "Steve Smith Sr.", "DeAngelo Williams"], "answer": 1},
    {"question": "What was the nickname of Seattle’s dominant defense in the early 2010s?", "choices": ["No Fly Zone", "The Sea Curtain", "The Sinister Secondary", "The Legion of Boom"], "answer": 3},
    {"question": "Which stadium is known for its deafening crowd noise and the “12th Man” tradition?", "choices": ["Lumen Field", "AT&T Stadium", "MetLife Field", "Mercedez-Benz Stadium"], "answer": 0},
    {"question": "Which player infamously threw the goal-line interception in Super Bowl XLIX?", "choices": ["Russell Wilson", "Tom Brady", "Donovan McNabb", "Steve McNair"], "answer": 0},
    {"question": "What is the oldest continuously running franchise in NFL history, dating back to 1898?", "choices": ["Packers", "Bears", "Giants", "Cardinals"], "answer": 3},
    {"question": "What was the nickname of the Rams’ early 2000s offense?", "choices": ["“The Air and Scare”", "“Rammers”", "“Legion of Zoom”", "“Greatest Show on Turf”"], "answer": 3},
    {"question": "Who caught the game-winning touchdown known as “The Hail Mary” from Roger Staubach?", "choices": ["Michael Irvin", "Billy Joe DuPree", "Golden Richards", "Drew Pearson"], "answer": 3},
    {"question": "Who was the first Cowboys player inducted into the Pro Football Hall of Fame?", "choices": ["Troy Aikman", "Roger Staubach", "Bob Lilly", "Emmitt Smith"], "answer": 2},
    {"question": "Which player threw the “Philly Special” touchdown in Super Bowl LII?", "choices": ["Alshon Jeffrey", "Zach Ertz", "Nelson Agholor", "Trey Burton"], "answer": 3},
    {"question": "Which Giants wide receiver made “The Helmet Catch”?", "choices": ["Victor Cruz", "Mario Manningham", "David Tyree", "Odell Beckham Jr."], "answer": 2},
    {"question": "Which wide receiver was famous for his one-handed catch on Sunday Night Football in 2014?", "choices": ["Antonio Brown", "Odell Beckham Jr", "Mike Evans", "Julio Jones"], "answer": 1},
    {"question": "Who was the head coach during Pittsburgh’s dynasty years of the 1970s?", "choices": ["Bill Walsh", "Joe Gibbs", "Don Shula", "Chuck Noll"], "answer": 3},
    {"question": "Which Steelers running back was nicknamed “The Bus”?", "choices": ["Mike Alstott", "Jerome Bettis", "Earl Campbell", "Franco Harris"], "answer": 1},
    {"question": "Which player caught the “Immaculate Reception”?", "choices": ["Rocky Bleier", "John Stallworth", "Lynn Swann", "Franco Harris"], "answer": 3},
    {"question": "What is the name of the Ravens’ mascot inspired by a famous poet?", "choices": ["Poe", "Spooky Bird", "Ray Ray the Raven", "Special Ed"], "answer": 0},
    {"question": "Which wide receiver caught the “Mile-High Miracle” in the 2012 playoffs?", "choices": ["Torrey Smith", "Jacoby Jones", "Anquan Boldin", "Tandon Doss"], "answer": 1},
    {"question": "What quarterback led the Browns to multiple championship appearances in the 1950s?", "choices": ["Norm Van Brocklin", "Jonny Unitas", "Otto Graham", "Sonny Jurgensen"], "answer": 2},
    {"question": "Which wide receiver earned the nickname “Ochocinco”?", "choices": ["Chad Johnson", "Greg Camarillo", "Tee Higgins", "Wesley Welker"], "answer": 0},
    {"question": "What Bengal was nicknamed “Ickey” for his famous post-TD dance, the Ickey Shuffle?", "choices": ["Rudi Johnson", "Cedric Benson", "James Brooks", "Elbert Woods"], "answer": 3},
    {"question": "Which running back earned the nickname “CJ2K” after rushing for over 2,000 yards in a season?", "choices": ["Chris Johnson", "CJ Gardner Johnson", "CJ Anderson", "Chad Johnson"], "answer": 0},
    {"question": "Which Tennessee Titans quarterback was named NFL MVP 2003?", "choices": ["Steve McNair", "Rich Gannon", "Warren Moon", "Kurt Warner"], "answer": 0},
    {"question": "What year did the Houston Oilers officially become the Tennessee Titans?", "choices": ["1997", "1999", "1996", "1995"], "answer": 1},
    {"question": "Which quarterback led the Jaguars to the AFC Championship Game during their second season in 1996?", "choices": ["Stan Humphries", "Mark Brunell", "Gus Frerotte", "Blake Bortles"], "answer": 1},
    {"question": "What was the nickname given to Jacksonville’s fierce defense during the 2017 season?", "choices": ["No Fly Zone", "Jax Attacks", "Thrashers", "Sacksonville"], "answer": 3},
    {"question": "Who was the Texans’ first-ever draft pick in franchise history?", "choices": ["Joey Harrington", "Jabar Gaffney", "Chester Pitts", "David Carr"], "answer": 3},
    {"question": "Which running back holds the Texans’ single-season rushing record?", "choices": ["Arian Foster", "Lamar Miller", "Steve Slaton", "Nick Chubb"], "answer": 0},
    {"question": "Who was the Chiefs’ legendary coach that led them to their first Super Bowl title in 1970?", "choices": ["Chuck Noll", "Lamar Hunt", "Hank Stram", "Vince Lombardi"], "answer": 2},
    {"question": "What year did the Chiefs draft Patrick Mahomes?", "choices": ["2014", "2018", "2017", "2019"], "answer": 2},
    {"question": "What was the Raiders’ famous team slogan coined by owner Al Davis?", "choices": ["“Just win, baby”", "“Show me your black hole!”", "“We the best!”", "“RAAAIIIDDERRSSSS, BABY!”"], "answer": 0},
    {"question": "Who was the first Broncos player to win NFL MVP?", "choices": ["Craig Morton", "Terrell Davis", "John Elway", "Peyton Manning"], "answer": 2},
    {"question": "Which Hall of Fame quarterback was known for “The Drive”?", "choices": ["John Elway", "Joe Montana", "Dan Marino", "Terry Bradshaw"], "answer": 0},
    {"question": "Which Running Back won NFL MVP in 2006?", "choices": ["LaDainian Tomlinson", "Edgerrin James", "Jamal Lewis", "Shaun Alexander"], "answer": 0},
    {"question": "Who was the Chargers’ Quarterback during the “Air Coryell” era?", "choices": ["Doug Flutie", "Stan Humphries", "Dan Fouts", "Philip Rivers"], "answer": 2},
    {"question": "What defensive player recorded the famous “pick-two” in 2016?", "choices": ["Derwin James", "Troy Polamalu", "Brian Dawkins", "Eric Berry"], "answer": 3},
    {"question": "What year did the Patriots complete a 16-0 regular season?", "choices": ["2004", "2011", "2007", "2001"], "answer": 2},
    {"question": "Who was the head coach during the Bills’ four consecutive Super Bowl appearances in the 1990s?", "choices": ["George Seifert", "Mike Holmgren", "Marv Levy", "Bill Parcells"], "answer": 2},
    {"question": "What kicker missed the potential game-winning field goal in Super Bowl XXV?", "choices": ["Blair Walsh", "Scott Norwood", "Adam Vinatieri", "Lin Elliott"], "answer": 1},
    {"question": "What year did the Dolphins complete the NFL’s only perfect season?", "choices": ["1972", "2007", "1975", "1967"], "answer": 0},
    {"question": "Which defensive player was nicknamed “The Mad Stork”?", "choices": ["Dick Butkus", "Deacon Jones", "Alan Page", "Ted Hendricks"], "answer": 3},
    {"question": "Which Quarterback famously guaranteed a Super Bowl win, and won?", "choices": ["Ken Stabler", "Bobby Layne", "Joe Namath", "Roger Staubach"], "answer": 2},
    {"question": "What was the name of the Lineman who got an ass full of Mark Sanchez in “The Butt Fumble”?", "choices": ["Brandon Moore", "D’Brickshaw Ferguson", "Nick Mangold", "Austin Howard"], "answer": 0},
    {"question": "True or False: Patrick Mahomes won a Super Bowl before turning 25.", "choices": ["True", "False"], "answer": 0},
    {"question": "True or False: Brett Favre threw more interceptions than touchdowns in his career.", "choices": ["False", "True"], "answer": 0},
    {"question": "True or False: No team has ever won the Super Bowl with a losing regular season record.", "choices": ["False", "True"], "answer": 1},
    {"question": "True or False: Brett Favre is the only QB to beat all 32 NFL teams.", "choices": ["False", "True"], "answer": 0},
    {"question": "True or False: Jerry Rice holds the record for most career fumbles by a non-QB.", "choices": ["False", "True"], "answer": 0},
    {"question": "True or False: Tom Brady has more playoff wins than any franchise.", "choices": ["True", "False"], "answer": 1},
    {"question": "True or False: The Cardinals franchise is older than the state of Arizona.", "choices": ["False", "True"], "answer": 1},
    {"question": "True or False: A kicker has won NFL MVP.", "choices": ["True", "False"], "answer": 0},
    {"question": "Which receiver caught Joe Montana’s game-winning touchdown in “The Catch”?", "choices": ["Dwight Clark", "Earl Cooper", "Ricky Patton", "Mike Wilson"], "answer": 0},
    {"question": "True or False: The Texans have reached a conference championship game.", "choices": ["True", "False"], "answer": 0},
    {"question": "True or False: The Packers won the first three Super Bowls.", "choices": ["True", "False"], "answer": 1},
    {"question": "Which WR caught the game winning TD against the Cardinals in the Super Bowl?", "choices": ["Hines Ward", "Larry Fitzgerald", "Santonio Holmes", "Nate Washington"], "answer": 2},
    {"question": "Which QB was drafted #1 overall in 2007?", "choices": ["Matthew Stafford", "Mario Williams", "JaMarcus Russell", "Reggie Bush"], "answer": 2},
    {"question": "True or False: Drew Brees won a League MVP award.", "choices": ["False", "True"], "answer": 1},
    {"question": "Which team's fan base is famous for throwing snowballs at Santa Claus?", "choices": ["Steelers", "Packers", "Browns", "Eagles"], "answer": 3},
    {"question": "Who was the youngest head coach to win a Super Bowl?", "choices": ["Jon Gruden", "John Madden", "Mike Tomlin", "Sean McVay"], "answer": 3},
    {"question": "Who is the heaviest player to throw a TD pass in NFL history at 346 lbs?", "choices": ["JaMarcus Russell", "Bubba Franks", "Trey Burton", "Dontario Poe"], "answer": 3},
    {"question": "The Tampa Bay Buccaneers were originally placed in which surprising division?", "choices": ["NFC Central", "AFC East", "NFC North", "AFC West"], "answer": 3},
    {"question": "How many teams did Ryan Fitzpatrick play for?", "choices": ["11", "10", "9", "7"], "answer": 2},
    {"question": "Who led the 2019 Dolphins in Rushing Yards?", "choices": ["Ryan Fitzpatrick", "Raheem Mostert", "Myles Gaskins", "Jeff Wilson Jr."], "answer": 0},
    {"question": "The Jets and Eagles have played each other since 1973. What year did the Jets first beat the Eagles?", "choices": ["1996", "2023", "2015", "1987"], "answer": 1},
    {"question": "True or False: The Packers have never won a game in Buffalo.", "choices": ["True", "False"], "answer": 0},
]
