
// ═══════════════════════════════════════════════════════════
// AUTO-GENERATED by Pigskin5 Question Generator
// Generated: 2026-04-17 14:27
// Days: 14
// ═══════════════════════════════════════════════════════════
// REVIEW CHECKLIST:
//   [ ] Spot-check 5 random answers for accuracy
//   [ ] Verify no duplicate questions across days
//   [ ] Check difficulty feels balanced
//   [ ] Merge into your main questions.js CALENDAR object
// ═══════════════════════════════════════════════════════════

    "2026-04-21": { //Tuesday
    event: "",
    questions: [
    { question: "Guess the Career TE:\n- 2,002 Rec. Yards\n- 16 Rec. TDs\n- 219 Receptions", choices: ["Dalton Schultz", "Kellen Winslow", "Cade Otton", "Logan Thomas"], answer: 3 },
    { question: "True or False: The Bears have won 2 Super Bowls.", choices: ["True", "False"], answer: 1 },
    { question: "OVER or UNDER: The Commanders have O/U 2.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "Who won Offensive Rookie of the Year in 2008?", choices: ["Matt Ryan", "Sterling Shepard", "T.J. Duckett", "Mike Gesicki"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Pig Prather", "Ja'Vontavious Van Der Berg", "Jammie Jammie-Jammie", "Dequavious Stormbreaker"], answer: 0 },
    ],
  },
    "2026-04-22": { //Wednesday
    event: "",
    questions: [
    { question: "True or False: The Super Bowl has been played on every day of the week at some point.", choices: ["True", "False"], answer: 1 },
    { question: "Who won MVP in 1999?", choices: ["David Carr", "Kurt Warner", "Tom Brady", "Mitchell Trubisky"], answer: 1 },
    { question: "Who is the Miami Dolphins' all-time leader in passing yards?", choices: ["Dan Marino", "Jacoby Brissett", "Tua Tagovailoa", "Teddy Bridgewater"], answer: 0 },
    { question: "OVER or UNDER: Michael Bennett has O/U 3,671.5 Career Rushing Yards.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Tretavious Humperdink", "D'Markus Fairweather", "Kayvontez Picklesworth", "Barkevious Mingo"], answer: 3 },
    ],
  },
    "2026-04-23": { //Thursday
    event: "",
    questions: [
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Yatil Green", "Deontarius Whistleblower", "Devontarius Dandridge", "Treshon Featherbottom"], answer: 0 },
    { question: "True or False: The Pittsburgh Steelers were originally called the Pittsburgh Pirates.", choices: ["True", "False"], answer: 0 },
    { question: "Which franchise originally drafted Russell Wilson?", choices: ["Seahawks", "49ers", "Dolphins", "Eagles"], answer: 0 },
    { question: "What year was the Vikings' first season?", choices: ["1961", "1966", "1964", "1968"], answer: 0 },
    { question: "Who led the NFL in Receptions in 2000?", choices: ["Jermaine Gresham", "Brandin Cooks", "Marvin Harrison", "Josh Gordon"], answer: 2 },
    ],
  },
    "2026-04-24": { //Friday
    event: "",
    questions: [
    { question: "True or False: The Jets won a Super Bowl before the Giants did.", choices: ["True", "False"], answer: 0 },
    { question: "OVER or UNDER: The Browns have O/U 0.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Who is the Indianapolis Colts' all-time leader in passing yards?", choices: ["Nick Foles", "Peyton Manning", "Daniel Jones", "Joe Flacco"], answer: 1 },
    { question: "Who holds the NFL record for most passing TDs in a single season?", choices: ["Baker Mayfield", "Tony Romo", "Josh McCown", "Peyton Manning"], answer: 3 },
    { question: "Guess the Career QB:\n- 64,128 Pass Yards\n- 418 Pass TDs\n- 211 INTs\n- 93.5 Passer Rating", choices: ["Carson Palmer", "Drew Brees", "Ben Roethlisberger", "John Elway"], answer: 2 },
    ],
  },
    "2026-04-25": { //Saturday
    event: "",
    questions: [
    { question: "Who led the NFL in Receptions in 2021?", choices: ["A.J. Brown", "Jakobi Meyers", "Cooper Kupp", "Delanie Walker"], answer: 2 },
    { question: "OVER or UNDER: The Chargers have O/U 0.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "True or False: Tom Brady has more division titles than the entire Jets franchise has in the Super Bowl era.", choices: ["True", "False"], answer: 0 },
    { question: "What overall pick number was JaMarcus Russell drafted at?", choices: ["14", "9", "8", "1"], answer: 3 },
    { question: "Guess the Career QB:\n- 11,522 Pass Yards\n- 66 Pass TDs\n- 62 INTs\n- 75.6 Passer Rating", choices: ["C.J. Stroud", "Gus Frerotte", "Rex Grossman", "Tyrod Taylor"], answer: 1 },
    ],
  },
    "2026-04-26": { //Sunday
    event: "",
    questions: [
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Aeneas Williams", "Treqwan Stormbreaker", "Jaiveon Crankshaw", "Hingle McCringleberry"], answer: 0 },
    { question: "Who won Defensive Rookie of the Year in 2020?", choices: ["Maxx Crosby", "Sauce Gardner", "Aaron Donald", "Chase Young"], answer: 3 },
    { question: "Guess the Career TE:\n- 2,098 Rec. Yards\n- 13 Rec. TDs\n- 224 Receptions", choices: ["Dennis Pitta", "Sam LaPorta", "Rob Gronkowski", "Daniel Graham"], answer: 0 },
    { question: "True or False: Drew Brees never won a League MVP award.", choices: ["True", "False"], answer: 0 },
    { question: "Who is the Los Angeles Rams' all-time leader in rushing yards?", choices: ["Sony Michel", "Cam Akers", "Eric Dickerson", "Kyren Williams"], answer: 2 },
    ],
  },
    "2026-04-27": { //Monday
    event: "",
    questions: [
    { question: "Who is the New Orleans Saints' all-time leader in passing yards?", choices: ["Jameis Winston", "Derek Carr", "Andy Dalton", "Drew Brees"], answer: 3 },
    { question: "What overall pick number was Russell Wilson drafted at?", choices: ["68", "87", "75", "69"], answer: 2 },
    { question: "Guess the Career TE:\n- 4,743 Rec. Yards\n- 39 Rec. TDs\n- 373 Receptions", choices: ["Alge Crumpler", "Cole Kmet", "Sam LaPorta", "L.J. Smith"], answer: 0 },
    { question: "OVER or UNDER: The Titans have O/U 0.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Which QB has more Career Passing Yards?", choices: ["Tom Brady", "Matthew Stafford", "Philip Rivers", "Eli Manning"], answer: 0 },
    ],
  },
    "2026-04-28": { //Tuesday
    event: "",
    questions: [
    { question: "How many longest fg return td did Antonio Cromartie record?", choices: ["95", "109", "96", "98"], answer: 1 },
    { question: "Which player caught the game-winning play in \"The Catch\"?", choices: ["Michael Vick", "Dwight Clark", "Kurt Warner", "Terrell Davis"], answer: 1 },
    { question: "True or False: The Kansas City Chiefs were originally called the Dallas Texans.", choices: ["True", "False"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Ventravian Hartfordshire", "Lavonte David", "Zecharion Pennywhistle", "Shaqavian St. Germaine"], answer: 1 },
    { question: "Guess the Career WR:\n- 5,384 Rec. Yards\n- 34 Rec. TDs\n- 364 Receptions", choices: ["Sammy Watkins", "Calvin Ridley", "Mike Wallace", "Corey Davis"], answer: 0 },
    ],
  },
    "2026-04-29": { //Wednesday
    event: "",
    questions: [
    { question: "Which coach led the Steelers to a Super Bowl victory?", choices: ["Herm Edwards", "Andy Reid", "Mike Tomlin", "Bill Belichick"], answer: 2 },
    { question: "How many receiving TDs did Randy Moss have in 2007?", choices: ["25", "19", "26", "23"], answer: 3 },
    { question: "OVER or UNDER: The Bears have O/U 9.5 NFL championships (all-time).", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "What year was the Titans' first season?", choices: ["1958", "1965", "1960", "1963"], answer: 2 },
    { question: "Guess the Career WR:\n- 10,514 Rec. Yards\n- 70 Rec. TDs\n- 727 Receptions", choices: ["Josh Gordon", "Chris Olave", "Tyrell Williams", "A.J. Green"], answer: 3 },
    ],
  },
    "2026-04-30": { //Thursday
    event: "",
    questions: [
    { question: "What year was the Packers' first season?", choices: ["1919", "1921", "1925", "1930"], answer: 0 },
    { question: "Which coach said the famous quote \"Playoffs?! Don't talk about playoffs!\"?", choices: ["John Madden", "Matt LaFleur", "Jim Mora", "Herm Edwards"], answer: 2 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Tresharius Dandridge", "Taco Charlton", "Zecharion Fairweather", "Ja'Quan McThunderson"], answer: 1 },
    { question: "Guess the All-Time WR:\n- 13,979 Rec. Yards\n- 139 Rec. TDs\n- 913 Receptions", choices: ["Randy Moss", "Bobby Engram", "Jerry Rice", "Terry Glenn"], answer: 0 },
    { question: "OVER or UNDER: The Raiders been located in O/U 2.5 cities.", choices: ["OVER", "UNDER"], answer: 0 },
    ],
  },
    "2026-05-01": { //Friday
    event: "",
    questions: [
    { question: "True or False: The Pittsburgh Steelers have always been called the Pittsburgh Steelers.", choices: ["True", "False"], answer: 1 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Ickey Woods", "Dequavious Quartermaine", "Quavondre Wainwright III", "Tavarius McThunderson"], answer: 0 },
    { question: "OVER or UNDER: Marquise Goodwin has O/U 3,070.5 Career Receiving Yards.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "Guess the All-Time QB:\n- 68,201 Pass Yards\n- 513 Pass TDs\n- 223 INTs\n- 98.1 Passer Rating", choices: ["Eli Manning", "John Elway", "Aaron Rodgers", "Peyton Manning"], answer: 3 },
    { question: "How many field goals did Rob Bironas make in his record single-game performance?", choices: ["7", "11", "9", "8"], answer: 3 },
    ],
  },
    "2026-05-02": { //Saturday
    event: "",
    questions: [
    { question: "OVER or UNDER: LeSean McCoy has O/U 11,152.5 Career Rushing Yards.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "True or False: An offensive lineman has caught a TD pass in the Super Bowl.", choices: ["True", "False"], answer: 1 },
    { question: "Which RB has more Career Rushing TDs?", choices: ["Eric Dickerson", "Marshawn Lynch", "Barry Sanders", "Shaun Alexander"], answer: 3 },
    { question: "Who is the Miami Dolphins' all-time leader in receiving yards?", choices: ["DeVante Parker", "Darren Waller", "Mark Duper", "Jonnu Smith"], answer: 2 },
    { question: "Guess the All-Time RB:\n- 13,259 Rush Yards\n- 90 Rush TDs\n- 4.4 Yards per Carry", choices: ["Tiki Barber", "Kevin Faulk", "Warrick Dunn", "Eric Dickerson"], answer: 3 },
    ],
  },
    "2026-05-03": { //Sunday
    event: "",
    questions: [
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Montravius Quartermaine", "Beezer Twelve Washingbeard", "Quandavious Bumbershoot", "Adoree' Jackson"], answer: 3 },
    { question: "In what year did \"Minneapolis Miracle\" occur?", choices: ["2017", "2020", "2014", "2019"], answer: 0 },
    { question: "Who holds the NFL record for most rushing TDs in a single season?", choices: ["LaDainian Tomlinson", "Julius Jones", "Melvin Gordon", "Leonard Fournette"], answer: 0 },
    { question: "OVER or UNDER: Philip Rivers has O/U 405.5 Career Passing TDs.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "True or False: The Texans have reached a conference championship game.", choices: ["True", "False"], answer: 1 },
    ],
  },
    "2026-05-04": { //Monday
    event: "",
    questions: [
    { question: "What year was the Cowboys' first season?", choices: ["1960", "1954", "1963", "1967"], answer: 0 },
    { question: "Guess the Career QB:\n- 24,154 Pass Yards\n- 149 Pass TDs\n- 106 INTs\n- 87.8 Passer Rating", choices: ["Daunte Culpepper", "Chad Pennington", "Jake Plummer", "Mark Brunell"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Devontavious McThunderclap", "Ziggy Ansah", "Javorius Blackenstein", "A.A. Ron Balakay"], answer: 1 },
    { question: "True or False: Joe Montana has won 5 Super Bowls.", choices: ["True", "False"], answer: 1 },
    { question: "What overall pick number was Bo Jackson drafted at?", choices: ["5", "1", "14", "9"], answer: 1 },
    ],
  },