
// ═══════════════════════════════════════════════════════════
// AUTO-GENERATED by Pigskin5 Question Generator
// Generated: 2026-08-15 13:42
// Days: 20
// ═══════════════════════════════════════════════════════════
// REVIEW CHECKLIST:
//   [ ] Spot-check 5 random answers for accuracy
//   [ ] Verify no duplicate questions across days
//   [ ] Check difficulty feels balanced
//   [ ] Merge into your main questions.js CALENDAR object
// ═══════════════════════════════════════════════════════════

    "2026-08-18": { //Tuesday
    event: "",
    questions: [
    { question: "Who had more receiving yards: Stefon Diggs (2020) or T.Y. Hilton (2016)?", choices: ["Stefon Diggs (2020)", "T.Y. Hilton (2016)"], answer: 0 },
    { question: "What division do the Pittsburgh Steelers play in?", choices: ["AFC East", "NFC West", "AFC North", "AFC South"], answer: 2 },
    { question: "True or False: 1928 was the Giants' first season.", choices: ["True", "False"], answer: 1 },
    { question: "Which player ate a W?", choices: ["Blake Bortles", "Richard Sherman", "Jameis Winston", "Jamaal Williams"], answer: 2 },
    { question: "Guess the Career QB:\n- 12,741 Pass Yards\n- 67 Pass TDs\n- 50 INTs\n- 86.9 Passer Rating", choices: ["Mac Jones", "Josh Freeman", "Mark Sanchez", "Joey Harrington"], answer: 0 },
    ],
  },
    "2026-08-19": { //Wednesday
    event: "",
    questions: [
    { question: "OVER or UNDER: Reggie Wayne has O/U 85 Career Receiving TDs.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Who won Super Bowl I?", choices: ["Cowboys", "Seahawks", "Packers", "Raiders"], answer: 2 },
    { question: "Guess the Career RB:\n- 2,054 Rush Yards\n- 9 Rush TDs\n- 4.0 Yards per Carry", choices: ["Danny Woodhead", "Doug Martin", "Ameer Abdullah", "Cordarrelle Patterson"], answer: 2 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Trevontay Junior", "Bismarck Rutherford-Hayes", "Chop Robinson", "Devon McNeail"], answer: 2 },
    { question: "True or False: The Baltimore Ravens play in the NFC South.", choices: ["True", "False"], answer: 1 },
    ],
  },
    "2026-08-20": { //Thursday
    event: "",
    questions: [
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Torque Lewith", "Ezekiel Wainwright III", "Trey'vor Junior", "Amen Ogbongbemiga"], answer: 3 },
    { question: "What is the name of the Ravens’ mascot inspired by a famous poet?", choices: ["Poe", "Spooky Bird", "Ray Ray the Raven", "Special Ed"], answer: 0 },
    { question: "Which coach led the Steelers to a Super Bowl victory?", choices: ["Andy Reid", "Mike Tomlin", "Dennis Green", "Vince Lombardi"], answer: 1 },
    { question: "Which NFL team plays their home games at Soldier Field?", choices: ["Baltimore Ravens", "Chicago Bears", "Indianapolis Colts", "Kansas City Chiefs"], answer: 1 },
    { question: "OVER or UNDER: The Rams have been located in O/U 3.5 cities.", choices: ["OVER", "UNDER"], answer: 1 },
    ],
  },
    "2026-08-21": { //Friday
    event: "",
    questions: [
    { question: "Who had more passing TDs: Drew Brees (2012) or Tom Brady (2007)?", choices: ["Drew Brees (2012)", "Tom Brady (2007)"], answer: 1 },
    { question: "Guess the Career RB:\n- 2,238 Rush Yards\n- 15 Rush TDs\n- 4.3 Yards per Carry\n- 32 Total TDs", choices: ["Jeff Wilson", "Jamaal Williams", "Darren McFadden", "Danny Woodhead"], answer: 3 },
    { question: "Which team did the Packers defeat in Super Bowl XXXI?", choices: ["Patriots", "Buccaneers", "Saints", "Bills"], answer: 0 },
    { question: "OVER or UNDER: The Colts have O/U 1.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "True or False: The Packers have won 5 Super Bowls.", choices: ["True", "False"], answer: 1 },
    ],
  },
    "2026-08-22": { //Saturday
    event: "",
    questions: [
    { question: "Guess the Career TE:\n- 2,277 Rec. Yards\n- 10 Rec. TDs\n- 206 Receptions", choices: ["Jordan Akins", "Greg Olsen", "Cade Otton", "George Kittle"], answer: 0 },
    { question: "OVER or UNDER: James Jones has O/U 60 Career Receiving TDs.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Who holds the NFL record for most career rushing yards?", choices: ["Frank Gore", "Steven Jackson", "Emmitt Smith", "Walter Payton"], answer: 2 },
    { question: "True or False: The Carolina Panthers play their home games at Bank of America Stadium.", choices: ["True", "False"], answer: 0 },
    { question: "What year did the Rams relocate to Los Angeles?", choices: ["2013", "2016", "2018", "2020"], answer: 1 },
    ],
  },
    "2026-08-23": { //Sunday
    event: "",
    questions: [
    { question: "Who is the Detroit Lions' all-time leader in receiving yards?", choices: ["Calvin Johnson", "Johnnie Morton", "Amon-Ra St. Brown", "Herman Moore"], answer: 0 },
    { question: "Which Hall of Famer was nicknamed \"The Minister of Defense\"?", choices: ["Reggie White", "Michael Strahan", "Mean Joe Greene", "Lawrence Taylor"], answer: 0 },
    { question: "Who had more rushing TDs: Derrick Henry (2019) or Shaun Alexander (2001)?", choices: ["Derrick Henry (2019)", "Shaun Alexander (2001)"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Trevontay Pennywhistle", "Jammie Jammie-Jammie", "Jermaine Fender", "Israel Idonije"], answer: 3 },
    { question: "In what season did the \"Fail Mary\" occur?", choices: ["2014", "2013", "2012", "2011"], answer: 2 },
    ],
  },
    "2026-08-24": { //Monday
    event: "",
    questions: [
    { question: "Guess the Career WR:\n- 3,311 Rec. Yards\n- 16 Rec. TDs\n- 256 Receptions", choices: ["DeSean Jackson", "Kendrick Bourne", "Devin Hester", "DK Metcalf"], answer: 2 },
    { question: "True or False: The Packers won the first two Super Bowls ever played.", choices: ["True", "False"], answer: 0 },
    { question: "What year was the Lions' first season?", choices: ["1930", "1928", "1924", "1933"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Quantrell Thundergood", "Craphonso Thorpe", "Ravioli Buccatini Sr.", "Lil'Jordan Henrich"], answer: 1 },
    { question: "How many receptions did Trey McBride have in 2025?", choices: ["131", "133", "126", "114"], answer: 2 },
    ],
  },
    "2026-08-25": { //Tuesday
    event: "",
    questions: [
    { question: "True or False: The Chicago Bears play their home games at Soldier Field.", choices: ["True", "False"], answer: 0 },
    { question: "Guess the Career QB:\n- 22,821 Pass Yards\n- 122 Pass TDs\n- 93 INTs\n- 84.4 Passer Rating", choices: ["Marc Bulger", "Trent Green", "Matt Cassel", "Lamar Jackson"], answer: 0 },
    { question: "Which NFL team plays their home games at Levi's Stadium?", choices: ["Buffalo Bills", "San Francisco 49ers", "Las Vegas Raiders", "Houston Texans"], answer: 1 },
    { question: "Who had more receptions: Torry Holt (2003) or Tony Gonzalez (2004)?", choices: ["Torry Holt (2003)", "Tony Gonzalez (2004)"], answer: 0 },
    { question: "Which coach said the famous quote \"They are who we thought they were!\"?", choices: ["Mike Ditka", "Andy Reid", "Dennis Green", "Vince Lombardi"], answer: 2 },
    ],
  },
    "2026-08-26": { //Wednesday
    event: "",
    questions: [
    { question: "How many Super Bowls have the Tennessee Titans won?", choices: ["2", "1", "0", "6"], answer: 2 },
    { question: "OVER or UNDER: The Cardinals have been located in O/U 3.5 cities.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Ozmatazz Buckshank", "Dick Butkus", "Ruke Johnson", "Trevontay Junior"], answer: 1 },
    { question: "Which team did the Broncos defeat in Super Bowl XXXIII?", choices: ["Buccaneers", "Falcons", "Dolphins", "Redskins"], answer: 1 },
    { question: "True or False: The Tennessee Titans were originally called the Houston Oilers.", choices: ["True", "False"], answer: 0 },
    ],
  },
    "2026-08-27": { //Thursday
    event: "",
    questions: [
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Tennison Butterfield", "J'Dinkalage Morgoone", "HaHa Clinton-Dix", "D'Glester Hardunkichud"], answer: 2 },
    { question: "True or False: Terry Bradshaw has won 5 Super Bowls.", choices: ["True", "False"], answer: 1 },
    { question: "Who was the head coach during Pittsburgh’s dynasty years of the 1970s?", choices: ["Bill Walsh", "Joe Gibbs", "Don Shula", "Chuck Noll"], answer: 3 },
    { question: "Which coach said the famous quote \"They are who we thought they were!\"?", choices: ["Dennis Green", "Matt LaFleur", "John Madden", "Jim Mora"], answer: 0 },
    { question: "Guess the Career RB:\n- 37 Rush TDs\n- 3.9 Yards per Carry\n- 39 Total TDs\n- 4,236 Rush Yards", choices: ["Rashard Mendenhall", "Cedric Benson", "Deuce McAllister", "Ryan Grant"], answer: 0 },
    ],
  },
    "2026-08-28": { //Friday
    event: "",
    questions: [
    { question: "True or False: The Houston Texans play their home games at NRG Stadium.", choices: ["True", "False"], answer: 0 },
    { question: "OVER or UNDER: The Browns have O/U 4.5 NFL championships (all-time).", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Who led the NFL in Rushing TDs in 2010?", choices: ["Clinton Portis", "Shaun Alexander", "Arian Foster", "LaDainian Tomlinson"], answer: 2 },
    { question: "Guess the Career WR:\n- 7,634 Rec. Yards\n- 41 Rec. TDs\n- 598 Receptions", choices: ["Don Hutson", "Terrell Owens", "Muhsin Muhammad", "Keyshawn Johnson"], answer: 3 },
    { question: "How many passing yards did Peyton Manning record in their record-setting 2013 season?", choices: ["4,978", "5,057", "5,477", "5,929"], answer: 2 },
    ],
  },
    "2026-08-29": { //Saturday
    event: "",
    questions: [
    { question: "True or False: Brett Favre was originally drafted by the Atlanta Falcons.", choices: ["True", "False"], answer: 0 },
    { question: "Who holds the NFL record for most passing TDs in a single season?", choices: ["Andy Dalton", "Kurt Warner", "Peyton Manning", "Drew Brees"], answer: 2 },
    { question: "Guess the Career RB:\n- 3,057 Rush Yards\n- 22 Rush TDs\n- 5.6 Yards per Carry\n- 35 Total TDs", choices: ["De'Von Achane", "David Johnson", "Antonio Gibson", "Jamaal Charles"], answer: 0 },
    { question: "OVER or UNDER: The Commanders have O/U 0.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "Who is the Kansas City Chiefs' all-time leader in rushing yards?", choices: ["Christian Okoye", "Jamaal Charles", "Larry Johnson", "Priest Holmes"], answer: 1 },
    ],
  },
    "2026-08-30": { //Sunday
    event: "",
    questions: [
    { question: "True or False: The San Francisco 49ers play their home games at Empower Field at Mile High.", choices: ["True", "False"], answer: 1 },
    { question: "In what season did the \"The Tackle\" occur?", choices: ["1999", "2000", "1997", "2002"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Adolfo Hartfordshire", "Trevontay Junior", "La'Quarine Quarterstein", "Jamari Thrash"], answer: 3 },
    { question: "Guess the Career TE:\n- 3,301 Rec. Yards\n- 18 Rec. TDs\n- 286 Receptions", choices: ["Coby Fleener", "Delanie Walker", "Shannon Sharpe", "Zach Miller"], answer: 2 },
    { question: "OVER or UNDER: The Titans have O/U 0.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 1 },
    ],
  },
    "2026-08-31": { //Monday
    event: "",
    questions: [
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Ventravian Martin III", "Quandavious Bumbershoot", "Shaqavian Hammersmith", "Ndamukong Suh"], answer: 3 },
    { question: "Who had more passing yards: Matthew Stafford (2025) or Drew Brees (2014)?", choices: ["Matthew Stafford (2025)", "Drew Brees (2014)"], answer: 0 },
    { question: "Guess the Career WR:\n- 14,345 Rec. Yards\n- 82 Rec. TDs\n- 1,070 Receptions", choices: ["Marques Colston", "Calvin Johnson", "Reggie Wayne", "Roddy White"], answer: 2 },
    { question: "What year did the Raiders relocate to Las Vegas?", choices: ["2020", "2015", "2026", "2023"], answer: 0 },
    { question: "True or False: Joe Montana has won 5 Super Bowls.", choices: ["True", "False"], answer: 1 },
    ],
  },
    "2026-09-01": { //Tuesday
    event: "",
    questions: [
    { question: "True or False: The Jaguars have appeared in a Super Bowl.", choices: ["True", "False"], answer: 1 },
    { question: "Guess the Career WR:\n- 5,220 Rec. Yards\n- 31 Rec. TDs\n- 402 Receptions", choices: ["Hines Ward", "David Boston", "Wayne Chrebet", "Peerless Price"], answer: 3 },
    { question: "Who holds the NFL record for most career rushing yards?", choices: ["Walter Payton", "Emmitt Smith", "Eric Dickerson", "Edgerrin James"], answer: 1 },
    { question: "OVER or UNDER: Clinton Portis has O/U 75 Career Total TDs.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Divine Deablo", "Bender Bonecastle", "Ja'Quan Allen-Finn", "Sofia Hartfordshire"], answer: 0 },
    ],
  },
    "2026-09-02": { //Wednesday
    event: "",
    questions: [
    { question: "OVER or UNDER: The Packers have O/U 13.5 NFL championships (all-time).", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Who is the NFL's all-time career leader in total touchdowns?", choices: ["Ed Dickson", "Cam Akers", "Bilal Powell", "Jerry Rice"], answer: 3 },
    { question: "True or False: The 49ers have won 6 Super Bowls.", choices: ["True", "False"], answer: 1 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Deontarius Bumbleton", "Jaqwellius Finnenbaum", "Breshawn Fairweather", "Rock Ya-Sin"], answer: 3 },
    { question: "Which QB has more Career Passing TDs?", choices: ["Eli Manning", "Russell Wilson", "Dan Marino", "John Elway"], answer: 2 },
    ],
  },
    "2026-09-03": { //Thursday
    event: "",
    questions: [
    { question: "What division do the Seattle Seahawks play in?", choices: ["NFC North", "NFC West", "AFC North", "AFC West"], answer: 1 },
    { question: "Which team was Eli Manning traded to on draft day?", choices: ["Cowboys", "Bears", "Jets", "Giants"], answer: 3 },
    { question: "Who led the NFL in Receiving Yards in 2005?", choices: ["Calvin Johnson", "Chad Johnson", "Steve Smith", "Reggie Wayne"], answer: 2 },
    { question: "Who was the first Broncos player to win NFL MVP?", choices: ["Craig Morton", "Terrell Davis", "John Elway", "Peyton Manning"], answer: 2 },
    { question: "OVER or UNDER: The Cardinals have been located in O/U 2.5 cities.", choices: ["OVER", "UNDER"], answer: 0 },
    ],
  },
    "2026-09-04": { //Friday
    event: "",
    questions: [
    { question: "OVER or UNDER: The Chargers have O/U 0.5 Super Bowl appearances all-time.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "Guess the Career QB:\n- 51,475 Pass Yards\n- 300 Pass TDs\n- 226 INTs\n- 79.9 Passer Rating", choices: ["Derek Carr", "Russell Wilson", "John Elway", "Ben Roethlisberger"], answer: 2 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Aeneas Williams", "Kayvontez Wainwright III", "George Van Der Berg", "Kendarious Feathers"], answer: 0 },
    { question: "Who had more rushing yards: Priest Holmes (2001) or Kareem Hunt (2017)?", choices: ["Priest Holmes (2001)", "Kareem Hunt (2017)"], answer: 0 },
    { question: "In what season did the \"Fail Mary\" occur?", choices: ["2012", "2009", "2015", "2011"], answer: 0 },
    ],
  },
    "2026-09-05": { //Saturday
    event: "",
    questions: [
    { question: "True or False: The Jets won a Super Bowl before the Giants did.", choices: ["True", "False"], answer: 0 },
    { question: "OVER or UNDER: The Raiders have O/U 3.5 Super Bowl victories all-time.", choices: ["OVER", "UNDER"], answer: 1 },
    { question: "Which franchise originally drafted Tony Mandarich?", choices: ["Seahawks", "Broncos", "Packers", "Raiders"], answer: 2 },
    { question: "What division do the Carolina Panthers play in?", choices: ["NFC South", "AFC South", "NFC West", "AFC West"], answer: 0 },
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Sofia Winterbottom", "Trevontay Fantloose", "D'Brickashaw Ferguson", "Jaqwellius Johnson"], answer: 2 },
    ],
  },
    "2026-09-06": { //Sunday
    event: "",
    questions: [
    { question: "Which of these was an ACTUAL NFL player?", choices: ["Fartrell Cluggins", "Tavarius Crumbleton", "Trindon Holliday", "Devon Marcus"], answer: 2 },
    { question: "OVER or UNDER: The Titans have O/U 0.5 Super Bowl appearances all-time.", choices: ["OVER", "UNDER"], answer: 0 },
    { question: "Which coach led the Raiders to a Super Bowl victory?", choices: ["Matt LaFleur", "Herm Edwards", "Mike Tomlin", "John Madden"], answer: 3 },
    { question: "True or False: A TE has led the league in receiving yards.", choices: ["True", "False"], answer: 1 },
    { question: "Which TE has more Career Receiving Yards?", choices: ["Jimmy Graham", "Antonio Gates", "Vernon Davis", "Rob Gronkowski"], answer: 1 },
    ],
  },